version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: microclinic
      POSTGRES_USER: microclinic_user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - appointment-service

  user-service:
    build:
      context: ./services/user-service
    env_file:
      - ./services/user-service/.env.example
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8001:8000"

  appointment-service:
    build:
      context: ./services/appointment-service
    env_file:
      - ./services/appointment-service/.env.example
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8002:8000"

volumes:
  pgdata:
